Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2021-08, with the labels that each got.

#208 feat, fix: Local library Manager reset function, stop creating file
  app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
Labels: Feature

#213 feat: Improve SourceCodeDialog
  app/src/main/java/mod/hey/studios/logic/SourceCodeDialog.java
Labels: enhancement

#223 feat: add option to show the source code of a single activity.
  app/src/main/java/a/a/a/yq.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
Labels: feature
