Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2023-08, with the labels that each got.

#946 Fix some issues related to information on not publishing swpro on app…
  README.md
Labels: documentation

#945 Fix a rare crash with parsing maven metadata
  app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
Labels: fix

#934 Fix: properly handle cases when dependency versions point to variables
  app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
  app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
  app/src/main/res/layout/library_downloader_dialog.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, fix, working on it

#953 Decompiled BaseWidget and related classes
  app/libs/a.a.a-notimportant-classes.jar
  app/libs/com.besome.sketch-classes.jar
  app/src/main/java/a/a/a/uy.java
  app/src/main/java/com/besome/sketch/editor/view/palette/IconBase.java
  app/src/main/java/com/besome/sketch/lib/base/BaseWidget.java
Labels: enhancement
