Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2023-07, with the labels that each got.

#898 bug fix when lib not download
  app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
Labels: fix

#905 feat: Ability to search for icons in ImportIconActivity
  app/src/main/java/com/besome/sketch/common/ImportIconActivity.java
  app/src/main/res/menu/menu_import_icon.xml
Labels: feature, good first contribution

#917 feat: Added badge in README file
  README.md
Labels: enhancement

#919 Greatly reduce time complexity with androidx dependencies
  app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
  app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
Labels: enhancement, fix
