Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2024-11, with the labels that each got.

#1358 Fix AppCompat Injection Manager
  app/src/main/java/dev/aldi/sayuti/editor/injection/AddCustomAttributeActivity.java
Labels: fix, merged

#1348 FIX : Empty Strings.xml error
  app/src/main/java/a/a/a/Zx.java
  app/src/main/java/com/besome/sketch/editor/property/PropertyInputItem.java
  app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
  app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
  app/src/main/java/mod/hilal/saif/blocks/BlocksHandler.java
  app/src/main/java/pro/sketchware/menu/ExtraMenuBean.java
  app/src/main/java/pro/sketchware/utility/FileUtil.java
Labels: fix, merged

#1372 fix: ImportIcon Toolbar Search icon not visible in Light Mode
  app/src/main/res/menu/menu_import_icon.xml
Labels: merged, UI/UX

#1342 New Relative Layout Widget
  app/libs/a.a.a-important-classes.jar
  app/src/main/java/a/a/a/Gx.java
  app/src/main/java/a/a/a/Ox.java
  app/src/main/java/a/a/a/ViewEditorFragment.java
  app/src/main/java/com/besome/sketch/beans/ViewBean.java
  app/src/main/java/com/besome/sketch/editor/property/PropertyAttributesItem.java
  app/src/main/java/com/besome/sketch/editor/property/ViewPropertyItems.java
  app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
  app/src/main/java/com/besome/sketch/editor/view/item/ItemRelativeLayout.java
  app/src/main/java/com/besome/sketch/editor/view/palette/IconRelativeLayout.java
  app/src/main/java/com/besome/sketch/editor/view/palette/PaletteWidget.java
  app/src/main/java/mod/elfilibustero/sketch/lib/utils/InjectAttributeHandler.java
  app/src/main/java/pro/sketchware/utility/InvokeUtil.java
  app/src/main/res/drawable/ic_property_parent_attr.xml
  app/src/main/res/layout/property_popup_parent_attr.xml
  app/src/main/res/values/strings.xml
Labels: feature, good first contribution

#1400 fix: crash if blocks.json is invalid json
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManager.java
Labels: fix, merged

#1399 feat: Improve another Dialogs
  app/src/main/java/mod/elfilibustero/sketch/lib/ui/SketchFilePickerDialog.java
  app/src/main/java/mod/jbk/editor/manage/library/ExcludeBuiltInLibrariesActivity.java
  app/src/main/res/layout/dialog_add_new_listener.xml
  app/src/main/res/layout/dialog_block_configuration.xml
  app/src/main/res/layout/dialog_palette.xml
  app/src/main/res/layout/dialog_select_apk_to_sign.xml
  app/src/main/res/layout/dialog_selector_actions.xml
  app/src/main/res/layout/widgets_creator_dialog.xml
Labels: merged, UI/UX

#1402 fix: Reset Button in PermissionManager not work
  app/src/main/java/mod/agus/jcoderz/editor/manage/permission/ManagePermissionActivity.java
Labels: fix, merged

#1396 Feat: icon maker + some fixes
  app/libs/a.a.a-notimportant-classes.jar
  app/src/main/AndroidManifest.xml
  app/src/main/assets/resource/600/res.zip
  app/src/main/java/a/a/a/Ix.java
  app/src/main/java/a/a/a/Zx.java
  app/src/main/java/a/a/a/lC.java
  app/src/main/java/a/a/a/sq.java
  app/src/main/java/a/a/a/yq.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
  app/src/main/java/com/besome/sketch/export/ExportProjectActivity.java
  app/src/main/java/com/besome/sketch/projects/MyProjectSettingActivity.java
  app/src/main/java/mod/hey/studios/project/backup/BackupRestoreManager.java
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManager.java
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java
  app/src/main/java/pro/sketchware/activities/coloreditor/ColorEditorActivity.java
  app/src/main/java/pro/sketchware/activities/coloreditor/adapters/ColorsAdapter.java
  app/src/main/java/pro/sketchware/activities/iconcreator/IconCreatorActivity.java
  app/src/main/java/pro/sketchware/activities/main/fragments/projects/ProjectsFragment.java
  app/src/main/java/pro/sketchware/lib/iconcreator/PatternBackgroundView.java
  app/src/main/res/color/bg_chip_states.xml
  app/src/main/res/drawable/ic_mtrl_arrow_down.xml
  app/src/main/res/drawable/ic_mtrl_arrow_left.xml
  app/src/main/res/drawable/ic_mtrl_arrow_right2.xml
  app/src/main/res/drawable/ic_mtrl_arrow_up.xml
  app/src/main/res/drawable/ic_mtrl_bltr.xml
  app/src/main/res/drawable/ic_mtrl_brtl.xml
  app/src/main/res/drawable/ic_mtrl_bt.xml
  app/src/main/res/drawable/ic_mtrl_circle.xml
  app/src/main/res/drawable/ic_mtrl_circle_small.xml
  app/src/main/res/drawable/ic_mtrl_lt.xml
  app/src/main/res/drawable/ic_mtrl_opacity_full.xml
  app/src/main/res/drawable/ic_mtrl_opacity_non.xml
  app/src/main/res/drawable/ic_mtrl_rotate_90.xml
  app/src/main/res/drawable/ic_mtrl_rotate_m90.xml
  app/src/main/res/drawable/ic_mtrl_rt.xml
  app/src/main/res/drawable/ic_mtrl_square.xml
  app/src/main/res/drawable/ic_mtrl_tlrb.xml
  app/src/main/res/drawable/ic_mtrl_top.xml
  app/src/main/res/drawable/ic_mtrl_trbl.xml
  app/src/main/res/drawable/icon_score_bg.xml
  app/src/main/res/drawable/pattern_seq.xml
  app/src/main/res/drawable/pattern_tech.xml
  app/src/main/res/drawable/pattern_waves.xml
  app/src/main/res/layout/color_editor_add.xml
  app/src/main/res/layout/dialog_advanced_version_control.xml
  app/src/main/res/layout/icon_creator_activity.xml
  app/src/main/res/layout/myproject_setting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles_new.xml
Labels: feature, fix, merged, UI/UX

#1353 Feat : Switched to a new working Implementation for APK/AAB signing
  app/build.gradle
  app/libs/build-tools_apksigner_32.0.0.jar
  app/src/main/java/com/besome/sketch/export/ExportProjectActivity.java
  app/src/main/java/mod/alucard/tn/apksigner/ApkSigner.java
  app/src/main/java/mod/hilal/saif/activities/tools/AppSettings.java
  app/src/main/java/mod/jbk/export/GetKeyStoreCredentialsDialog.java
  app/src/main/java/pro/sketchware/utility/apk/ApkSignerUtils.java
  app/src/main/res/layout/dialog_keystore_credentials.xml
  app/src/minApi26/java/mod/jbk/util/TestkeySignBridge.java
Labels: enhancement

#1411 Fix Code Generation
  app/src/main/java/a/a/a/Fx.java
Labels: fix

#1416 feat: Improve FilePicker UI
  app/src/main/java/com/github/angads25/filepicker/controller/adapters/FileListAdapter.java
  app/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java
  app/src/main/java/com/github/angads25/filepicker/widget/MaterialCheckbox.java
  app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
  app/src/main/java/mod/hey/studios/activity/managers/assets/ManageAssetsActivity.java
  app/src/main/java/mod/hey/studios/activity/managers/java/ManageJavaActivity.java
  app/src/main/java/mod/hey/studios/activity/managers/nativelib/ManageNativelibsActivity.java
  app/src/main/java/mod/hey/studios/util/Helper.java
  app/src/main/java/mod/hilal/saif/activities/tools/AppSettings.java
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerDetailsActivity.java
  app/src/main/java/pro/sketchware/fragments/settings/events/EventsManagerFragment.java
  app/src/main/res/layout/dialog_file_list_item.xml
  app/src/main/res/layout/dialog_footer.xml
  app/src/main/res/layout/dialog_header.xml
  app/src/main/res/values/styles_new.xml
Labels: UI/UX

#1420 style, refactor: redesign and use `ViewBinding` for `PropertiesDialogs`
  app/src/main/java/a/a/a/aB.java
  app/src/main/java/com/besome/sketch/editor/property/PropertyIndentItem.java
  app/src/main/java/com/besome/sketch/editor/property/PropertyInputItem.java
  app/src/main/java/com/besome/sketch/editor/property/PropertyMeasureItem.java
  app/src/main/res/layout/property_popup_input_size.xml
  app/src/main/res/values/strings.xml
Labels: UI/UX

#1376 feat: Generate View Binding classes for layouts
  app/src/main/java/a/a/a/Hx.java
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/a/a/a/Lx.java
  app/src/main/java/a/a/a/ProjectBuilder.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
  app/src/main/java/com/besome/sketch/projects/MyProjectSettingActivity.java
  app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
  app/src/main/java/mod/hey/studios/editor/manage/block/code/ExtraBlockCode.java
  app/src/main/java/mod/hey/studios/project/ProjectSettings.java
  app/src/main/java/mod/hey/studios/project/ProjectSettingsDialog.java
  app/src/main/java/mod/pranav/viewbinding/ViewBindingBuilder.kt
  app/src/main/java/pro/sketchware/activities/main/fragments/projects_store/ProjectPreviewActivity.java
  app/src/main/res/layout/dialog_project_settings.xml
  app/src/main/res/layout/main.xml
Labels: feature

#1462 feat: add `edit`, `export`, and `import` actions for `customWidgets`
  app/src/main/java/a/a/a/ViewEditorFragment.java
  app/src/main/java/com/besome/sketch/editor/view/ViewEditor.java
  app/src/main/java/com/besome/sketch/editor/view/palette/PaletteWidget.java
  app/src/main/java/pro/sketchware/widgets/IconCustomWidget.java
  app/src/main/java/pro/sketchware/widgets/WidgetsCreatorManager.java
  app/src/main/res/menu/widget_creator_menu_more.xml
  app/src/main/res/values/strings.xml
Labels: feature
