Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2024-10, with the labels that each got.

#1290 feat, style: Suggestions for inject, remove colors definition of AutoCompleteTextView style
  app/src/main/java/com/besome/sketch/editor/property/PropertyInputItem.java
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles_new.xml
Labels: enhancement

#1291 feat: Add service option in view selector & improve AddViewActivity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/anim/locked.lottie
  app/src/main/java/a/a/a/Ix.java
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/a/a/a/ViewEditorFragment.java
  app/src/main/java/com/besome/sketch/ProjectsAdapter.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/com/besome/sketch/editor/manage/ViewSelectorActivity.java
  app/src/main/java/com/besome/sketch/editor/manage/view/AddViewActivity.java
  app/src/main/java/mod/hey/studios/util/ProjectFile.java
  app/src/main/res/layout/fr_graphic_editor.xml
  app/src/main/res/layout/manage_screen_activity_add_temp.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI/UX

#1300 Added strings editor
  app/src/main/AndroidManifest.xml
  app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
  app/src/main/java/mod/bobur/StringEditorActivity.java
  app/src/main/res/layout/string_editor.xml
  app/src/main/res/layout/string_editor_item.xml
  app/src/main/res/layout/view_string_editor_add.xml
Labels: feature

#1315 Fix appcompat attributes deletion
  app/src/main/java/dev/aldi/sayuti/editor/injection/AddCustomAttributeActivity.java
Labels: fix

#1311 Improve Project preview and add transitions
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/besome/sketch/MainActivity.java
  app/src/main/java/com/besome/sketch/fragments/projects_store/ProjectPreviewActivity.java
  app/src/main/java/com/besome/sketch/fragments/projects_store/ProjectPreviewFragment.java
  app/src/main/java/com/besome/sketch/fragments/projects_store/adapters/StorePagerProjectsAdapter.java
  app/src/main/java/com/besome/sketch/fragments/projects_store/adapters/StoreProjectsAdapter.java
  app/src/main/java/com/besome/sketch/fragments/projects_store/api/ProjectModel.java
  app/src/main/java/mod/ilyasse/utils/UI.java
  app/src/main/java/mod/tyron/backup/SingleCopyAsyncTask.java
  app/src/main/java/mod/tyron/backup/SingleCopyTask.kt
  app/src/main/res/layout/fragment_projects_store.xml
  app/src/main/res/layout/fragment_store_project_preview.xml
  app/src/main/res/layout/view_store_project_item.xml
Labels: enhancement, UI/UX

#1328 Feat : Color Editor + minor bug fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/a/a/a/Zx.java
  app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
  app/src/main/java/mod/bobur/StringEditorActivity.java
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManager.java
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java
  app/src/main/java/pro/sketchware/activities/coloreditor/ColorEditorActivity.java
  app/src/main/java/pro/sketchware/activities/coloreditor/adapters/ColorsAdapter.java
  app/src/main/java/pro/sketchware/activities/coloreditor/models/ColorItem.java
  app/src/main/java/pro/sketchware/utility/XmlUtil.java
  app/src/main/res/layout/color_editor_activity.xml
  app/src/main/res/layout/color_editor_add.xml
  app/src/main/res/layout/custom_dialog_attribute.xml
  app/src/main/res/layout/dialog.xml
  app/src/main/res/layout/pallet_customview.xml
  app/src/main/res/values/strings.xml
Labels: feature, merged

#1343 Small adjustment
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
Labels: fix, merged
