Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2024-12, with the labels that each got.

#1463 fix: Firebase configuration not saved when clicking back in toolbar
  app/src/main/java/com/besome/sketch/editor/manage/library/firebase/FirebaseActivity.java
Labels: fix

#1484 feat: Allow open another text files
  app/src/main/java/mod/hey/studios/activity/managers/assets/ManageAssetsActivity.java
Labels: feature

#1498 feat: redesign VarTypeSelector dialog
  app/src/main/java/a/a/a/gt.java
  app/src/main/res/layout/var_type_category.xml
  app/src/main/res/layout/var_type_item.xml
  app/src/main/res/layout/var_type_selector_dialog.xml
  app/src/main/res/layout/var_type_spinner.xml
  app/src/main/res/layout/var_type_spinner_dialog.xml
  app/src/main/res/layout/var_type_spinner_item.xml
  app/src/main/res/menu/var_type_selector_menu.xml
Labels: good first contribution, UI/UX

#1517 fix, perf: optimize Local Library Search
  app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
Labels: fix

#1522 fix: Resolve crash when click in unknow view
  app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
Labels: fix

#1504 Feat : drag and drop to arrange in blocks manager
  app/src/main/java/mod/hilal/saif/activities/tools/BlocksManager.java
  app/src/main/res/drawable/ic_mtrl_drag.xml
  app/src/main/res/layout/blocks_manager.xml
  app/src/main/res/layout/pallet_customview.xml
Labels: feature, UI/UX

#1511 Vector image
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/a/a/a/pu.java
  app/src/main/java/a/a/a/tx.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
  app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
  app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
  app/src/main/java/mod/bobur/XmlToSvgConverter.java
  app/src/main/java/pro/sketchware/activities/coloreditor/ColorEditorActivity.java
Labels: feature

#1526 Redesign bottom layout of DesignActivity
  app/src/main/java/com/besome/sketch/adapters/JavaFileAdapter.java
  app/src/main/java/com/besome/sketch/beans/ProjectFileBean.java
  app/src/main/java/com/besome/sketch/design/DesignActivity.java
  app/src/main/java/com/besome/sketch/editor/view/ProjectFileSelector.java
  app/src/main/java/com/besome/sketch/export/ExportProjectActivity.java
  app/src/main/java/dev/aldi/sayuti/editor/manage/LibraryDownloaderDialogFragment.java
  app/src/main/java/mod/hey/studios/build/BuildSettings.java
  app/src/main/java/mod/hey/studios/build/BuildSettingsDialog.java
  app/src/main/java/mod/hey/studios/project/proguard/ProguardHandler.java
  app/src/main/java/mod/hey/studios/project/stringfog/StringfogHandler.java
  app/src/main/java/mod/jbk/build/BuildProgressReceiver.java
  app/src/main/java/mod/jbk/build/BuiltInLibraries.java
  app/src/main/java/mod/jbk/build/compiler/resource/ResourceCompiler.java
  app/src/main/res/drawable/ic_mtrl_run.xml
  app/src/main/res/drawable/ic_mtrl_screen.xml
  app/src/main/res/drawable/ic_mtrl_stop.xml
  app/src/main/res/layout/design.xml
  app/src/main/res/layout/project_config_layout.xml
  app/src/main/res/menu/design_bottom_menu.xml
  app/src/minApi26/java/mod/hey/studios/compiler/kotlin/KotlinCompilerBridge.java
Labels: working on it, UI/UX

#1533 Feat: changing recyclerview view to navigation rail in collection manager
  app/src/main/java/com/besome/sketch/editor/manage/ManageCollectionActivity.java
  app/src/main/res/drawable/ic_mtrl_moreblock.xml
  app/src/main/res/layout/manage_collection.xml
  app/src/main/res/layout/manage_collection_block_list_item.xml
  app/src/main/res/layout/manage_collection_more_block_list_item.xml
  app/src/main/res/layout/manage_collection_widget_list_item.xml
  app/src/main/res/menu/manage_collection_items_menu.xml
Labels: UI/UX

#1547 feat : Export Logcat for logcat reader
  app/src/main/java/mod/khaled/logcat/LogReaderActivity.java
  app/src/main/java/pro/sketchware/utility/FileUtil.java
  app/src/main/res/menu/menu_logcat.xml
Labels: feature
