Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2025-06, with the labels that each got.

#1664 Fixed selector edit fonction saving title and name in wrong order
  app/src/main/java/pro/sketchware/fragments/settings/block/selector/BlockSelectorManagerFragment.java
Labels: fix

#1678 Fix: Correct screen reader announcement order for blocks
  app/src/main/java/com/besome/sketch/editor/logic/PaletteBlock.java
Labels: fix

#1689 feat: Use MaterialToolbar if Material 3 Is Enable
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/a/a/a/Ox.java
  app/src/main/java/a/a/a/mq.java
Labels: improvement

#1682 refactor, fix and optimize about activites and fragments
  app/src/main/java/pro/sketchware/activities/about/fragments/BetaChangesFragment.java
Labels: improvement, fix
