Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2025-08, with the labels that each got.

#1808 Material design theme customizer
  app/src/main/java/a/a/a/yq.java
  app/src/main/java/com/besome/sketch/projects/MyProjectSettingActivity.java
  app/src/main/java/com/besome/sketch/projects/ThemeManager.java
  app/src/main/java/com/besome/sketch/projects/ThemePresetAdapter.java
  app/src/main/java/mod/hey/studios/lib/code_editor/CodeEditorLayout.java
  app/src/main/java/mod/hey/studios/lib/code_editor/ColorScheme.java
  app/src/main/java/mod/hey/studios/lib/code_editor/ColorTheme.java
  app/src/main/res/drawable/theme_preset_item_selector.xml
  app/src/main/res/layout/myproject_setting.xml
  app/src/main/res/layout/theme_preset_item.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1832 fix: string.xml button in input dialog not working correcly
  app/src/main/java/com/besome/sketch/editor/property/PropertyInputItem.java
Labels: fix

#1862 featuring latest material dependencies update of alpha channel
  app/build.gradle
Labels: dependency
