Repository Sketchware-Pro/Sketchware-Pro, pull requests merged in 2025-03, with the labels that each got.

#1609 fix: Correct package name for View Binding classess
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/mod/pranav/viewbinding/ViewBindingBuilder.kt
Labels: fix, merged

#1617 Revert "fix: Correct package name for View Binding classess"
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/mod/pranav/viewbinding/ViewBindingBuilder.kt
Labels: fix, revert

#1622 fix: refine viewBinding implementation in block selector menu
  app/src/main/java/a/a/a/Fx.java
  app/src/main/java/a/a/a/Jx.java
  app/src/main/java/a/a/a/Lx.java
  app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
  app/src/main/java/mod/agus/jcoderz/editor/event/ManageEvent.java
  app/src/main/res/layout/dialog_project_settings.xml
Labels: fix
